#!/bin/bash

$HOME/.config/polybar/launch.sh --bspwm

function run {
  if (command -v $1 && ! pgrep $1); then
    $@&
  fi
}

sxhkd &
run numlockx &
run picom &
run nitrogen --restore &
run volumeicon &
run nm-applet &

bspc monitor -d web term code files media mail

bspc config focus_follows_pointer true
bspc config window_gap 15
bspc config border_width 0
bspc config split_ratio 0.52

bspc rule -a Xed state=floating
bspc rule -a Engrampa state=floating
