#!/bin/bash
if [ $1 == "--delayed" ]; then
    sleep 10 ; xfce4-screenshooter -r ; paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
elif [ $1 == "-r" ]; then
    xfce4-screenshooter -r ; paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
else
   xfce4-screenshooter -f; paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
fi


